# Generated by Django 5.0.6 on 2024-05-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='apellidos',
            new_name='ciudad_estado',
        ),
        migrations.AddField(
            model_name='registros',
            name='correo',
            field=models.CharField(default='S/N', max_length=50),
        ),
        migrations.AddField(
            model_name='registros',
            name='empresa',
            field=models.CharField(default='S/N', max_length=50),
        ),
        migrations.AddField(
            model_name='registros',
            name='num_telefono',
            field=models.CharField(default='S/N', max_length=50),
        ),
    ]
