# Generated by Django 5.0.6 on 2024-05-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_rename_apellidos_registros_ciudad_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='codigo_barras',
            field=models.CharField(default='S/N', max_length=50),
        ),
    ]
